apiVersion: apps/v1
kind: Deployment
metadata:
  name: busapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busapp
  template:
    metadata:
      labels:
        app: busapp
    spec:
      containers:
      - name: busapp
        image: learnitguide/busapp
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "200m"
            memory: "128Mi"
