apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: busapp-ingress
spec:
  rules:
    - host: busapp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: busapp-service
                port:
                  number: 80
